### ISSUE TITLE
Update to Swift 5

### ISSUE THREAD

**Issue by fury21** [mrigdon/MRArticleViewController#5]
Hi!
Update pls this wonderful project to swift 5. 
Than u!!!

**Comment by stamizharasu** [comment]
Hello,

I too would like this to be updated to the latest Swift.

Any idea on the timeline for this?

**Comment by mrigdon-zz** [comment]
sorry for the delayed response. @fury21 @stamizharasu is the swift 5 upgrade still desired?

**Comment by stamizharasu** [comment]
@mrigdon Yes, if possible. I'm currently blocked due to the lack of version upgrades.

**Comment by mrigdon-zz** [comment]
@stamizharasu  my apologies. will begin work on this immediately.
